[package]
name = "runtime-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
servo = "0.1"
winit = { version = "0.30", features = ["rwh_06"] }
euclid.workspace = true
url.workspace = true
tracing.workspace = true
thiserror.workspace = true
raw-window-handle = "0.6"
rustls = { version = "0.23", features = ["aws-lc-rs"] }
